services:
  bot:
    build: .
    container_name: nitneeds_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////app/data/users.db
    volumes:
      - ./data:/app/data
